on:
  push:
    branches:
      - 'main'
    paths:
      - '*.yml'
name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: .flatpak-builder
        key: flatpak-build-${{ github.sha }}
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: kadas.flatpak
        manifest-path: com.sourcepole.kadas.yml
        cache: false
