on:
  push:
    branches:
      - 'main'
    paths:
      - '*.yml'
  pull_request:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: .flatpak-builder
        key: flatpak-build-${{ github.sha }}
        restore-keys: flatpak-build
        
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: qgis.flatpak
        manifest-path: org.qgis.qgis.yml
        cache: false
